require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AmmountsController do

  # This should return the minimal set of attributes required to create a valid
  # Ammount. As you add validations to Ammount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2015-03-02" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AmmountsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ammounts as @ammounts" do
      ammount = Ammount.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ammounts).should eq([ammount])
    end
  end

  describe "GET show" do
    it "assigns the requested ammount as @ammount" do
      ammount = Ammount.create! valid_attributes
      get :show, {:id => ammount.to_param}, valid_session
      assigns(:ammount).should eq(ammount)
    end
  end

  describe "GET new" do
    it "assigns a new ammount as @ammount" do
      get :new, {}, valid_session
      assigns(:ammount).should be_a_new(Ammount)
    end
  end

  describe "GET edit" do
    it "assigns the requested ammount as @ammount" do
      ammount = Ammount.create! valid_attributes
      get :edit, {:id => ammount.to_param}, valid_session
      assigns(:ammount).should eq(ammount)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ammount" do
        expect {
          post :create, {:ammount => valid_attributes}, valid_session
        }.to change(Ammount, :count).by(1)
      end

      it "assigns a newly created ammount as @ammount" do
        post :create, {:ammount => valid_attributes}, valid_session
        assigns(:ammount).should be_a(Ammount)
        assigns(:ammount).should be_persisted
      end

      it "redirects to the created ammount" do
        post :create, {:ammount => valid_attributes}, valid_session
        response.should redirect_to(Ammount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ammount as @ammount" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ammount.any_instance.stub(:save).and_return(false)
        post :create, {:ammount => { "date" => "invalid value" }}, valid_session
        assigns(:ammount).should be_a_new(Ammount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ammount.any_instance.stub(:save).and_return(false)
        post :create, {:ammount => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ammount" do
        ammount = Ammount.create! valid_attributes
        # Assuming there are no other ammounts in the database, this
        # specifies that the Ammount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ammount.any_instance.should_receive(:update).with({ "date" => "2015-03-02" })
        put :update, {:id => ammount.to_param, :ammount => { "date" => "2015-03-02" }}, valid_session
      end

      it "assigns the requested ammount as @ammount" do
        ammount = Ammount.create! valid_attributes
        put :update, {:id => ammount.to_param, :ammount => valid_attributes}, valid_session
        assigns(:ammount).should eq(ammount)
      end

      it "redirects to the ammount" do
        ammount = Ammount.create! valid_attributes
        put :update, {:id => ammount.to_param, :ammount => valid_attributes}, valid_session
        response.should redirect_to(ammount)
      end
    end

    describe "with invalid params" do
      it "assigns the ammount as @ammount" do
        ammount = Ammount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ammount.any_instance.stub(:save).and_return(false)
        put :update, {:id => ammount.to_param, :ammount => { "date" => "invalid value" }}, valid_session
        assigns(:ammount).should eq(ammount)
      end

      it "re-renders the 'edit' template" do
        ammount = Ammount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ammount.any_instance.stub(:save).and_return(false)
        put :update, {:id => ammount.to_param, :ammount => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ammount" do
      ammount = Ammount.create! valid_attributes
      expect {
        delete :destroy, {:id => ammount.to_param}, valid_session
      }.to change(Ammount, :count).by(-1)
    end

    it "redirects to the ammounts list" do
      ammount = Ammount.create! valid_attributes
      delete :destroy, {:id => ammount.to_param}, valid_session
      response.should redirect_to(ammounts_url)
    end
  end

end
