require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FuturesController do

  # This should return the minimal set of attributes required to create a valid
  # Future. As you add validations to Future, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "account_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FuturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all futures as @futures" do
      future = Future.create! valid_attributes
      get :index, {}, valid_session
      assigns(:futures).should eq([future])
    end
  end

  describe "GET show" do
    it "assigns the requested future as @future" do
      future = Future.create! valid_attributes
      get :show, {:id => future.to_param}, valid_session
      assigns(:future).should eq(future)
    end
  end

  describe "GET new" do
    it "assigns a new future as @future" do
      get :new, {}, valid_session
      assigns(:future).should be_a_new(Future)
    end
  end

  describe "GET edit" do
    it "assigns the requested future as @future" do
      future = Future.create! valid_attributes
      get :edit, {:id => future.to_param}, valid_session
      assigns(:future).should eq(future)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Future" do
        expect {
          post :create, {:future => valid_attributes}, valid_session
        }.to change(Future, :count).by(1)
      end

      it "assigns a newly created future as @future" do
        post :create, {:future => valid_attributes}, valid_session
        assigns(:future).should be_a(Future)
        assigns(:future).should be_persisted
      end

      it "redirects to the created future" do
        post :create, {:future => valid_attributes}, valid_session
        response.should redirect_to(Future.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved future as @future" do
        # Trigger the behavior that occurs when invalid params are submitted
        Future.any_instance.stub(:save).and_return(false)
        post :create, {:future => { "account_id" => "invalid value" }}, valid_session
        assigns(:future).should be_a_new(Future)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Future.any_instance.stub(:save).and_return(false)
        post :create, {:future => { "account_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested future" do
        future = Future.create! valid_attributes
        # Assuming there are no other futures in the database, this
        # specifies that the Future created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Future.any_instance.should_receive(:update).with({ "account_id" => "1" })
        put :update, {:id => future.to_param, :future => { "account_id" => "1" }}, valid_session
      end

      it "assigns the requested future as @future" do
        future = Future.create! valid_attributes
        put :update, {:id => future.to_param, :future => valid_attributes}, valid_session
        assigns(:future).should eq(future)
      end

      it "redirects to the future" do
        future = Future.create! valid_attributes
        put :update, {:id => future.to_param, :future => valid_attributes}, valid_session
        response.should redirect_to(future)
      end
    end

    describe "with invalid params" do
      it "assigns the future as @future" do
        future = Future.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Future.any_instance.stub(:save).and_return(false)
        put :update, {:id => future.to_param, :future => { "account_id" => "invalid value" }}, valid_session
        assigns(:future).should eq(future)
      end

      it "re-renders the 'edit' template" do
        future = Future.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Future.any_instance.stub(:save).and_return(false)
        put :update, {:id => future.to_param, :future => { "account_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested future" do
      future = Future.create! valid_attributes
      expect {
        delete :destroy, {:id => future.to_param}, valid_session
      }.to change(Future, :count).by(-1)
    end

    it "redirects to the futures list" do
      future = Future.create! valid_attributes
      delete :destroy, {:id => future.to_param}, valid_session
      response.should redirect_to(futures_url)
    end
  end

end
